version: '3'
services:
  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    ports:
      - '8086:8086'
    networks:
      - iot
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD = ${INFLUXDB_USER_PASSWORD}
      
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_USER_TOKEN}
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    networks:
      - iot
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    command: >
      bash -c "grafana-server --homepath=/usr/share/grafana && sleep 10 && curl -X POST 'http://${GRAFANA_USERNAME}:${GRAFANA_PASSWORD}@localhost:3000/api/datasources' -H 'Content-Type: application/json' -d '{\"name\":\"InfluxDB\",\"type\":\"influxdb\",\"access\":\"proxy\",\"url\":\"http://influxdb:8086\",\"jsonData\":{\"organization\":\"${DOCKER_INFLUXDB_INIT_ORG}\",\"defaultBucket\":\"${DOCKER_INFLUXDB_INIT_BUCKET}\",\"version\":\"Flux\", \"tlsSkipVerify\":\"true\"},\"secureJsonData\":{\"token\":\"${INFLUXDB_USER_TOKEN}\"}}' && sleep 10 && curl -X POST 'http://${GRAFANA_USERNAME}:${GRAFANA_PASSWORD}@localhost:3000/api/dashboards/db' -H 'Content-Type: application/json' -d @/grafana-dashboard.json"
  


    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_DATABASE_NAME=${INFLUXDB_DB}
      - GF_DATABASE_USER=${INFLUXDB_USER}
      - GF_DATABASE_PASSWORD=${INFLUXDB_USER_PASSWORD}
    #  - GF_DATABASE_URL=http://influxdb:8086

      
networks:
  iot:

volumes:
  influxdb_data:
  influxdb_config:
  grafana_data:
